### ISSUE TITLE
ygo的卡图 都是日文的, 大佬知道在哪搞中文卡图吗

### ISSUE THREAD

**Issue by liushengliuyun** [Nightended/YGO-Print_PDF#1]

**Comment by Nightended** [comment]
中文卡图一般都是在本地进行渲染，真正的中文卡图找起来并不容易...

**Comment by liushengliuyun** [comment]
我发现用萌卡下载ygo pro2的卡图全是中文, 但是清晰度不够 。 即使用了ai修复 ， 文字也只是提高了锐度， 还是看不清

**Comment by liushengliuyun** [comment]
后面我就从网页生成了， https://ygo.ygosgs.com/#/yugioh。 可以根据卡密直接生成， 就是不能批量。

**Comment by Nightended** [comment]
可以参考一下这个项目 https://github.com/kooriookami/yugioh-card ，对前端熟悉的话可以尝试自己构建一个，可惜我现在需要学习的东西比较多……

**Comment by liushengliuyun** [comment]
厉害。 有个优化建议， 卡图之间可以不留空隙， 这样切图的时候可以少切几刀。

**Comment by Nightended** [comment]
这个项目已经没有维护的打算了，这也是作为初学者的测试项目，使用起来也受很多的限制，并且还需要配置环境什么的，已经违背了方便的初中，以后可能会用c#重新尝试一下？切图的话，当时就是因为这个网页出的图都连在一起不好切割而放弃了https://proxy-card.imasanari.dev/
